"""stricter_rules

Revision ID: 6041737510bc
Revises: 8f01056ccb8f
Create Date: 2026-08-11 23:44:17.469436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6041737510bc'
down_revision: Union[str, Sequence[str], None] = '8f01056ccb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_unique_constraint(None, 'leads', ['phone'])
    op.create_unique_constraint(None, 'leads', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    # ### end Alembic commands ###
