version: "3.8"
services:
  eea_db:
    image: postgres:15
    env_file:
      - .env.services
    restart: unless-stopped
    volumes:
      - eea_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

volumes:
  eea_data:
